cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: AKIAVDCEONAUMGZMHDYJ
      secret-key: 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
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/350183385128/springboot-testing-queue
spring:
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            id: AUTO

            instanceName: myScheduler

          jobStore:
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
    jdbc:
      initialize-schema: always
  #            dataSource: aa
  datasource:
    username: root
    password: ${DB_PWD}
    url: jdbc:mysql://localhost:3306/${DATABASE}
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    properties:
      hibernate:
        bytecode:
          use_reflection_optimizer: false
        provider: org.hibernate.bytecode.internal.none.None
        generate_statistics: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: springboot-aws-services
logging:
  level:
    org:
      springframework: DEBUG
      hibernate:
        stat: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: '*, openapi, swagger-ui'
      base-path: /management
server:
  port: 8081
  servlet:
    contextPath: /springboot-aws-services
springdoc:
  show-actuator: true
  swagger-ui:
    path: /documentation
    enabled: true
  api-docs:
    path: /api-docs
    enabled: true
  group-configs:
    - group: Testing APIs
      paths-to-match: /test/**
    - group: Admin Management
      paths-to-match: /management/**
    - group: Animal APIs
      paths-to-match: /pet/**
    - group: AWS SQS
      paths-to-match: /aws/sqs/**
application:
  auth:
    roles:
      USER:
        username: ${USER_USERNAME}
        password: ${USER_PWD}
      ADMIN:
        username: ${ADMIN_USERNAME}
        password: ${ADMIN_PWD}
#http://localhost:8081/springboot-aws-services/documentation
#http://localhost:8081/springboot-aws-services/swagger-ui/index.html